### ISSUE TITLE
Audio modality with only 73 features instead of 6373

### ISSUE THREAD

**Issue by pedrobisp** [SenticNet/contextual-utterance-level-multimodal-sentiment-analysis#1]
When using the create_data.py script, it prints the shapes for the train and test sets from each modality. I have the following being printed out:

./data/text/text
Mapping train
Mapping test
(62L, 63L, 100L) (31L, 63L, 100L) 62 31
Dumping data
./data/audio/audio
Mapping train
Mapping test
(62L, 63L, 73L) (31L, 63L, 73L) 62 31
Dumping data
./data/video/video
Mapping train
Mapping test
(62L, 63L, 100L) (31L, 63L, 100L) 62 31
Dumping data

The paper mentions openSMILE being used to extract the 6373 features per utterance, but this is not what we are seeing here. Same thing concerning the arff and csv files under data/audio: Only 73 features per utterance. Why is that?

**Comment by amirim** [comment]
Hi,

I checked their input and it's 74 audio features.

**Comment by SenticNet** [comment]
We had done some feature selection to do that.
