### ISSUE TITLE
training process

### ISSUE THREAD

**Issue by amirim** [SenticNet/contextual-utterance-level-multimodal-sentiment-analysis#4]
Hi,

I ran the training, and the results are:
`Epoch 66/200`
and then the confusion matrix is printed and:
`Accuracy  0.780585106383` 

Why does the training finish after 66 epochs and not 200 (maybe then the accuracy would be greater)?

What do I need to change in the code in order to run this training on MOSEI?

**Comment by SenticNet** [comment]
This happens because of early_stopping. To know early_stopping please read any ML book.

To run on MOSEI you need to make the data in a way that the utterances are linked.
