### ISSUE TITLE
network diagram

### ISSUE THREAD

**Issue by amirim** [SenticNet/contextual-utterance-level-multimodal-sentiment-analysis#8]
Hi,

Thank you for your contribution, I read the paper and your code and prepared the attached diagram. 
Please correct me if I'm wrong about any of the layers. It would be grateful if you in return would explain your choices like the activation layers, hyper-parametrs etc. 

[
![tri modal](https://user-images.githubusercontent.com/32954177/39993821-dcfaf38c-577f-11e8-8f83-2e7705a317d9.jpg)
](url)

**Comment by SenticNet** [comment]
Yes this is correct but please note that the utterances are actually linked to each other using LSTM connections.
